services:
  django:
    build: ../backend/docker_env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - C:/Users/Niki/Desktop/moneybook/backend/:/usr/src/backend
    environment:
      - POSTGRES_NAME=Finance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
      - 3000:3000